### ISSUE TITLE
Transfer to Spotify org?

### ISSUE THREAD

**Issue by hexedpackets** [spotify/ffwd-client-java#1]
A few [Spotify repos](https://github.com/udoprog/ffwd-client-java/network/dependents) are using this client, and ffwd itself is under the Spotify org of course. We would like to transfer the ffwd-client to the Spotify org so we can make sure it stays updated with changes to ffwd.

What do you think @udoprog?

**Comment by udoprog** [comment]
Sounds good to me. Thanks for the suggestion!

**Comment by udoprog** [comment]
@hexedpackets I can't seem transfer ownership to an organization I'm not a member of. I'm guessing you'll have to temporarily add me to the Spotify org. If you have any other suggestion I'm open to it. Otherwise is that OK?

**Comment by udoprog** [comment]
Actually, I've requested to transfer it to you now @hexedpackets, if you accept you can transfer it to the Spotify org afterwards.

**Comment by hexedpackets** [comment]
That works, thanks!
